jobs:
  Build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: 21
    - continue-on-error: true
      name: Grant execute permission to gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build
    - continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: Compiled artifacts for ${{ github.sha }}
        path: build/libs
name: Development Builds
on:
  repository_dispatch:
    types: trigger-ga___devbuild.yml
